name: Generate GitHub Streak Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once every day at midnight UTC
  workflow_dispatch:      # Allows you to trigger manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Streak SVG
        run: |
          mkdir -p assets
          curl "https://streak-stats.demolab.com/?user=AnasHasan786&theme=dark&hide_border=true" -o assets/streak.svg

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/streak.svg
          git commit -m "Update GitHub streak stats"
          git push
