name: 🧠 GitHub Metrics

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AnasHasan786
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          # ✅ Language Insights
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_limit: 8
          plugin_languages_ignored: html
          plugin_languages_indepth: yes

          # ✅ Top Repositories
          plugin_repositories: yes
          plugin_repositories_featured: AnasHasan786/SustainaWare--AI-Powered-Waste-Classification-and-Recycling-System, AnasHasan786/FoodVision
          plugin_repositories_order: featured, pinned, starred, random

          # ✅ Followers + Stars
          plugin_followup: yes
          plugin_stars: yes

          # ✅ Traffic (Profile visits)
          plugin_traffic: yes
